from typing import Any, List, Tuple
class Reader:
    def __init__(self, languages: Any, *args: Any, **kwargs: Any): ...
    def readtext(self, img: Any, *args: Any, **kwargs: Any) -> List[Tuple[Any, str, float]]: ... 