from typing import Any
def imread(*args: Any, **kwargs: Any) -> Any: ...
def resize(*args: Any, **kwargs: Any) -> Any: ...
def cvtColor(*args: Any, **kwargs: Any) -> Any: ...
COLOR_BGR2GRAY: int
INTER_AREA: int 