name: Block sensitive files
on: [push, pull_request]
jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Fail on sensitive file patterns
        run: |
          set -euo pipefail
          # Check changed files on push/PR
          git diff --name-only origin/${{ github.base_ref || "HEAD^" }}...HEAD > changed.txt || true
          PATTERN="\.(db|db-shm|db-wal|sqlite|bak|backup|log)$"
          if grep -E "$PATTERN" changed.txt; then
            echo "::error::Sensitive file pattern detected. Add to .gitignore or remove."
            exit 1
          fi
