name: Single-Port Owlin Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test single-port server
      run: |
        # Start server in background
        python -m backend.final_single_port &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 3
        
        # Run smoke tests
        pytest tests/test_single_port_smoke.py -v
        
        # Clean up
        kill $SERVER_PID
